x-common: &common
  build: .
  env_file: .env
  restart: unless-stopped

services:
  eth-ydegen:
    <<: *common
    container_name: eth-ydegen
    environment:
      NETWORK: ethereum
      RPC_URL: ${ETH_RPC_URL}

  arb-ydegen:
    <<: *common
    container_name: arb-ydegen
    environment:
      NETWORK: arbitrum
      RPC_URL: ${ARB_RPC_URL}

  katana-ydegen:
    <<: *common
    container_name: katana-ydegen
    environment:
      NETWORK: katana
      RPC_URL: ${KATANA_RPC_URL}
