x-common: &common
  build: .
  env_file: .env
  restart: unless-stopped

services:
  eth-vaults-mommy:
    <<: *common
    container_name: eth-vaults-mommy
    environment:
      NETWORK: ethereum
      RPC_URL: ${ETH_RPC_URL}

  arb-vaults-mommy:
    <<: *common
    container_name: arb-vaults-mommy
    environment:
      NETWORK: arbitrum
      RPC_URL: ${ARB_RPC_URL}

  katana-vaults-mommy:
    <<: *common
    container_name: katana-vaults-mommy
    environment:
      NETWORK: katana
      RPC_URL: ${KATANA_RPC_URL}

  base-vaults-mommy:
    <<: *common
    container_name: base-vaults-mommy
    environment:
      NETWORK: base
      RPC_URL: ${BASE_RPC_URL}

  op-vaults-mommy:
    <<: *common
    container_name: op-vaults-mommy
    environment:
      NETWORK: optimism
      RPC_URL: ${OP_RPC_URL}
