name: Build Bot Image

on:
  push:
    branches: [main]

jobs:
  build:
    if: false  # never runs. remove this line to re-enable build once base image supports Python >=3.12
    name: Build without pushing
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        uses: SilverbackLtd/build-action@v1
