name: Build Bot Image

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build without pushing
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        uses: SilverbackLtd/build-action@v1
